service: myBackpacks

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  stage: dev
  profile: janMatzek
  architecture: x86_64
  timeout: 30
  memorySize: 1024
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: backpack_runner.json

functions:
  backpackScraper:
    handler: scraper.handler
    layers:
      # - arn:aws:lambda:us-east-1:730335547446:layer:python-pandas-layer
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: /scrapeBackpacks
          method: get
          cors: true
          authorizer: null

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 1
  serverless-offline:
    noTimeout: true
  pythonRequirements:
    useDownloadCache: false
    layer: true
    slim: true
    usePoetry: false
    dockerizePip: true

package:
  patterns:
    - "!__pycache__/**"
    - "!.vscode/**"
    - "!venv/**"
    - "!.venv/**"
    - "!.gitignore"
    - "!requirements.txt"
    - "!.git/**"
    - "!.gitignore"
    - "!.gitmodules"
    - "!__pycache__/**"
    - "!serverless/**"
    - "!.serverless_plugins/**"
    - "!.DS_Store"
    - "!.env"
    - "!backpack_runner.json"
    - "!requirements"
    - "!**/*.csv"
    - "!.vscode/**"
    - "!readme.MD"
